<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Eccube\Entity\Calendar;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends AbstractRepository
{
    /**
     * CalendarRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Calendar::class);
    }

    /**
     * 管理ユーザの表示順を一つ上げる.
     *
     * @param Calendar $Calendar
     *
     * @throws \Exception 更新対象のユーザより上位のユーザが存在しない場合.
     */
    public function cal($value)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.date >= :date')
            ->setParameter('date', $value)
            ->orderBy('c.id', 'ASC');
        $Calendar = $qb->getQuery()
            ->getResult();
        return $Calendar;
    }

}
